### ISSUE TITLE
I would like to compile the org.eclipse.linuxtools project myself. How should I proceed?

### ISSUE THREAD

**Issue by laomaolaile** [eclipse-linuxtools/org.eclipse.linuxtools#355]
I have tried to use the mvn install command to compile the org.eclipse.linuxtools project, but I've encountered various errors. I feel unable to resolve these errors myself. Could you please share how you compile the org.eclipse.linuxtools project? Do you use any other tools?

![image](https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/assets/19726057/f78f5149-15cf-4849-bf46-a9bf7b578952)

![image](https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/assets/19726057/a138fa5b-9ac8-40b9-85c8-757cdbde1c5c)

My Java version is java 21, and my Maven version is Maven 3.9.6.

![image](https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/assets/19726057/fa870d09-cac8-4c05-a435-57c48c0cf3e4)

Looking forward to your reply.thanks

**Comment by laomaolaile** [comment]
Yes, I am using the master branch. I have also tried other targets, but I am still encountering errors.
@akurtakov

**Comment by akurtakov** [comment]
Have you managed to compile? If not, make sure that you pull latest from this repo master, git status should show no changes and retry. The output saying linuxtools-e4.31 shows you're not using latest.

**Comment by laomaolaile** [comment]
I can compile it normally now, thank you very much.

There are two issues.

 Firstly, my Java version is too low. Previously, when compiling embedded cdt, Java 17 was sufficient, while the latest version of org. eclipse. linuxtools requires Java 21.

The second question, my branch https://download.eclipse.org/eclipse/updates/4.31-I-builds/ Unable to access, after switching to the latest branch, it will return to normal. Perhaps it would be better to use CDT's p2 address directly here?

@akurtakov

**Comment by akurtakov** [comment]
This is development version and it requires Java 21. Furthermore it relies on very latest Platform ( https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/blob/cc82f0df922b6d707a8b16c787fa01a4853cb4dc/releng/org.eclipse.linuxtools.target/linuxtools-e4.32.target#L39 ) and very latest CDT ( https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/blob/cc82f0df922b6d707a8b16c787fa01a4853cb4dc/releng/org.eclipse.linuxtools.target/linuxtools-e4.32.target#L55 )  and this is in order to ensure that this development version will work with very latest Platform and CDT.
If you want to work on e.g.  stable-8.14 branch , edit https://github.com/eclipse-linuxtools/org.eclipse.linuxtools/blob/e0c5927e088810fd66650f30b4d033a2b177be5f/releng/org.eclipse.linuxtools.target/linuxtools-e4.31.target#L39 to use the stable 4.31 url https://download.eclipse.org/eclipse/updates/4.31/ . Note that you may have to do the same for CDT.
As you are able to compile master I am closing this one now.
